/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace IMixedRouteQuoterV1 {
  export type QuoteExactInputSingleStableParamsStruct = {
    tokenIn: AddressLike;
    tokenOut: AddressLike;
    amountIn: BigNumberish;
    flag: BigNumberish;
  };

  export type QuoteExactInputSingleStableParamsStructOutput = [
    tokenIn: string,
    tokenOut: string,
    amountIn: bigint,
    flag: bigint
  ] & { tokenIn: string; tokenOut: string; amountIn: bigint; flag: bigint };

  export type QuoteExactInputSingleV2ParamsStruct = {
    tokenIn: AddressLike;
    tokenOut: AddressLike;
    amountIn: BigNumberish;
  };

  export type QuoteExactInputSingleV2ParamsStructOutput = [
    tokenIn: string,
    tokenOut: string,
    amountIn: bigint
  ] & { tokenIn: string; tokenOut: string; amountIn: bigint };

  export type QuoteExactInputSingleV3ParamsStruct = {
    tokenIn: AddressLike;
    tokenOut: AddressLike;
    amountIn: BigNumberish;
    fee: BigNumberish;
    sqrtPriceLimitX96: BigNumberish;
  };

  export type QuoteExactInputSingleV3ParamsStructOutput = [
    tokenIn: string,
    tokenOut: string,
    amountIn: bigint,
    fee: bigint,
    sqrtPriceLimitX96: bigint
  ] & {
    tokenIn: string;
    tokenOut: string;
    amountIn: bigint;
    fee: bigint;
    sqrtPriceLimitX96: bigint;
  };
}

export interface QuoterV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "WETH9"
      | "deployer"
      | "factory"
      | "factoryStable"
      | "factoryV2"
      | "pancakeV3SwapCallback"
      | "quoteExactInput"
      | "quoteExactInputSingleStable"
      | "quoteExactInputSingleV2"
      | "quoteExactInputSingleV3"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "WETH9", values?: undefined): string;
  encodeFunctionData(functionFragment: "deployer", values?: undefined): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "factoryStable",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "factoryV2", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pancakeV3SwapCallback",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "quoteExactInput",
    values: [BytesLike, BigNumberish[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "quoteExactInputSingleStable",
    values: [IMixedRouteQuoterV1.QuoteExactInputSingleStableParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "quoteExactInputSingleV2",
    values: [IMixedRouteQuoterV1.QuoteExactInputSingleV2ParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "quoteExactInputSingleV3",
    values: [IMixedRouteQuoterV1.QuoteExactInputSingleV3ParamsStruct]
  ): string;

  decodeFunctionResult(functionFragment: "WETH9", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deployer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "factoryStable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "factoryV2", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pancakeV3SwapCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "quoteExactInput",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "quoteExactInputSingleStable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "quoteExactInputSingleV2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "quoteExactInputSingleV3",
    data: BytesLike
  ): Result;
}

export interface QuoterV2 extends BaseContract {
  connect(runner?: ContractRunner | null): QuoterV2;
  waitForDeployment(): Promise<this>;

  interface: QuoterV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  WETH9: TypedContractMethod<[], [string], "view">;

  deployer: TypedContractMethod<[], [string], "view">;

  factory: TypedContractMethod<[], [string], "view">;

  factoryStable: TypedContractMethod<[], [string], "view">;

  factoryV2: TypedContractMethod<[], [string], "view">;

  pancakeV3SwapCallback: TypedContractMethod<
    [amount0Delta: BigNumberish, amount1Delta: BigNumberish, path: BytesLike],
    [void],
    "view"
  >;

  quoteExactInput: TypedContractMethod<
    [path: BytesLike, flag: BigNumberish[], amountIn: BigNumberish],
    [
      [bigint, bigint[], bigint[], bigint] & {
        amountOut: bigint;
        v3SqrtPriceX96AfterList: bigint[];
        v3InitializedTicksCrossedList: bigint[];
        v3SwapGasEstimate: bigint;
      }
    ],
    "nonpayable"
  >;

  quoteExactInputSingleStable: TypedContractMethod<
    [params: IMixedRouteQuoterV1.QuoteExactInputSingleStableParamsStruct],
    [bigint],
    "view"
  >;

  quoteExactInputSingleV2: TypedContractMethod<
    [params: IMixedRouteQuoterV1.QuoteExactInputSingleV2ParamsStruct],
    [bigint],
    "view"
  >;

  quoteExactInputSingleV3: TypedContractMethod<
    [params: IMixedRouteQuoterV1.QuoteExactInputSingleV3ParamsStruct],
    [
      [bigint, bigint, bigint, bigint] & {
        amountOut: bigint;
        sqrtPriceX96After: bigint;
        initializedTicksCrossed: bigint;
        gasEstimate: bigint;
      }
    ],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "WETH9"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "deployer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "factory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "factoryStable"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "factoryV2"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pancakeV3SwapCallback"
  ): TypedContractMethod<
    [amount0Delta: BigNumberish, amount1Delta: BigNumberish, path: BytesLike],
    [void],
    "view"
  >;
  getFunction(
    nameOrSignature: "quoteExactInput"
  ): TypedContractMethod<
    [path: BytesLike, flag: BigNumberish[], amountIn: BigNumberish],
    [
      [bigint, bigint[], bigint[], bigint] & {
        amountOut: bigint;
        v3SqrtPriceX96AfterList: bigint[];
        v3InitializedTicksCrossedList: bigint[];
        v3SwapGasEstimate: bigint;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "quoteExactInputSingleStable"
  ): TypedContractMethod<
    [params: IMixedRouteQuoterV1.QuoteExactInputSingleStableParamsStruct],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "quoteExactInputSingleV2"
  ): TypedContractMethod<
    [params: IMixedRouteQuoterV1.QuoteExactInputSingleV2ParamsStruct],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "quoteExactInputSingleV3"
  ): TypedContractMethod<
    [params: IMixedRouteQuoterV1.QuoteExactInputSingleV3ParamsStruct],
    [
      [bigint, bigint, bigint, bigint] & {
        amountOut: bigint;
        sqrtPriceX96After: bigint;
        initializedTicksCrossed: bigint;
        gasEstimate: bigint;
      }
    ],
    "nonpayable"
  >;

  filters: {};
}
